import { useState, useEffect, useRef } from 'react';
import { X, Trash2, Save, MapPin, Navigation, Calendar, Search, Ticket, Map } from 'lucide-react';
import server from '../api/gas';

/**
 * Smart EditModal - Phase 1
 * - bookingRef field for all categories
 * - Editable from field (auto-filled but overridable)
 * - Name with Places suggestions for non-transport
 * - Auto-fill from from previous event
 */
const EditModal = ({ isOpen, onClose, item, onSave, onDelete, previousEvent, availableDates = [], currentDate }) => {
    const [formData, setFormData] = useState({});
    const [suggestions, setSuggestions] = useState([]);
    const [showSuggestions, setShowSuggestions] = useState(false);
    const [activeSuggestionField, setActiveSuggestionField] = useState(null); // 'name', 'to', 'from'
    const [selectedDate, setSelectedDate] = useState(currentDate || '');
    const suggestionsTimeoutRef = useRef(null);

    // Common place suggestions (fallback when API unavailable)
    const commonPlaces = [
        '中部国際空港 (セントレア)', '那覇空港', '名古屋駅', '東京駅', '新宿駅',
        '京都駅', '大阪駅', '博多駅', '札幌駅', '高山駅', '下呂駅', '飛騨古川駅',
        '沖縄美ら海水族館', '首里城', '国際通り', '万座毛', 'ホテル日航アリビラ',
        'リザンシーパークホテル谷茶ベイ', 'ANAインターコンチネンタル万座ビーチリゾート'
    ];

    // Auto-fill from previous event
    const autoFrom = previousEvent?.to || previousEvent?.address || previousEvent?.name || '';

    useEffect(() => {
        if (!isOpen) return;

        if (item) {
            // For transport events, separate customName from auto-generated name
            const isItemTransport = ['flight', 'train', 'bus'].includes(item.category);
            const autoGeneratedName = isItemTransport && item.from && item.to
                ? `${item.from} → ${item.to}`
                : '';
            const customName = isItemTransport && item.name !== autoGeneratedName
                ? item.name
                : '';

            setFormData({
                ...item,
                from: item.from || autoFrom,
                customName: customName
            });
        } else {
            setFormData({
                type: 'activity',
                category: 'sightseeing',
                status: 'planned',
                time: '10:00',
                name: '',
                from: autoFrom,
                customName: ''
            });
        }
        setSelectedDate(currentDate || '');
        setSuggestions([]);
        setShowSuggestions(false);
        // We intentionally omit item, currentDate, autoFrom to prevents form resets during editing
        // Re-initialization should only happen when the modal is opened or the target item fundamentally changes
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isOpen, item?.name, item?.time, item?.category]); // Only re-init if specific identifier properties change

    // Cleanup timeout on unmount to prevent memory leaks
    useEffect(() => {
        return () => {
            if (suggestionsTimeoutRef.current) {
                clearTimeout(suggestionsTimeoutRef.current);
            }
        };
    }, []);

    const isTransport = ['flight', 'train', 'bus'].includes(formData.category);

    // Fetch suggestions (using GAS Places Autocomplete API with local fallback)
    const fetchSuggestions = async (query) => {
        if (!query || query.length < 2) {
            setSuggestions([]);
            return;
        }

        try {
            // Try GAS Places Autocomplete API
            const result = await server.getPlaceAutocomplete(query);
            if (result.predictions && result.predictions.length > 0) {
                setSuggestions(result.predictions);
            } else {
                // Fallback to local suggestions
                const filtered = commonPlaces.filter(p =>
                    p.toLowerCase().includes(query.toLowerCase())
                ).slice(0, 5);
                setSuggestions(filtered.map(p => ({ description: p, placeId: null })));
            }
        } catch {
            // Fallback to local suggestions on error
            const filtered = commonPlaces.filter(p =>
                p.toLowerCase().includes(query.toLowerCase())
            ).slice(0, 5);
            setSuggestions(filtered.map(p => ({ description: p, placeId: null })));
        }
    };

    // Handle input change with debounced suggestions
    const handleInputWithSuggestions = (field, value) => {
        const updates = { [field]: value };
        setFormData({ ...formData, ...updates });

        if (suggestionsTimeoutRef.current) {
            clearTimeout(suggestionsTimeoutRef.current);
        }
        suggestionsTimeoutRef.current = setTimeout(() => {
            fetchSuggestions(value);
            setActiveSuggestionField(field);
            setShowSuggestions(true);
        }, 300);
    };

    const selectSuggestion = (suggestion) => {
        const description = typeof suggestion === 'string' ? suggestion : suggestion.description;
        const updates = { [activeSuggestionField]: description };
        if (activeSuggestionField === 'to' && isTransport) {
            updates.name = description;
        }
        if (activeSuggestionField === 'name' && !isTransport) {
            // For non-transport, name selection could also set address
            updates.address = description;
        }
        setFormData({ ...formData, ...updates });
        setShowSuggestions(false);
        setSuggestions([]);
    };

    // Open Google Maps for a location
    const openMap = (location) => {
        if (!location) return;
        const url = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(location)}`;
        window.open(url, '_blank');
    };

    const closeSuggestions = () => {
        setTimeout(() => setShowSuggestions(false), 200);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-modal flex items-end sm:items-center justify-center bg-black/50 p-0 sm:p-4" onClick={onClose}>
            <div className="bg-white dark:bg-slate-800 w-full max-w-full sm:max-w-lg rounded-t-2xl sm:rounded-2xl shadow-2xl flex flex-col max-h-[90vh] sm:max-h-[85vh] animate-slide-up-spring overflow-hidden" onClick={e => e.stopPropagation()}>
                {/* Header */}
                <div className="px-4 py-3 border-b border-gray-100 dark:border-slate-700 flex justify-between items-center shrink-0">
                    <h3 className="font-bold text-lg text-gray-800 dark:text-slate-100">{item ? '予定を編集' : '新しい予定'}</h3>
                    <button onClick={onClose} className="p-2 hover:bg-gray-100 dark:hover:bg-slate-700 rounded-lg transition-colors">
                        <X size={20} className="text-gray-500" />
                    </button>
                </div>

                {/* Form Content */}
                <div className="p-4 overflow-y-auto overflow-x-hidden space-y-4 flex-1">
                    {/* Category & Status */}
                    <div className="flex flex-wrap gap-3">
                        <div className="flex-1 min-w-[120px]">
                            <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">カテゴリ</label>
                            <select
                                value={formData.category || ''}
                                onChange={e => setFormData({ ...formData, category: e.target.value })}
                                className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl border-0 text-gray-800 dark:text-slate-100 text-sm font-medium"
                            >
                                <option value="flight">✈️ 飛行機</option>
                                <option value="train">🚄 電車</option>
                                <option value="bus">🚌 バス</option>
                                <option value="sightseeing">📍 観光</option>
                                <option value="meal">🍽️ 食事</option>
                                <option value="hotel">🏨 宿泊</option>
                            </select>
                        </div>
                        <div className="flex-1 min-w-[120px]">
                            <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">ステータス</label>
                            <select
                                value={formData.status || ''}
                                onChange={e => setFormData({ ...formData, status: e.target.value })}
                                className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl border-0 text-gray-800 dark:text-slate-100 text-sm font-medium"
                            >
                                <option value="planned">📋 計画中</option>
                                <option value="confirmed">✅ 確定</option>
                                <option value="suggested">💡 候補</option>
                            </select>
                        </div>
                    </div>

                    {/* Date Change */}
                    {item && availableDates.length > 1 && (
                        <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-xl p-3">
                            <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 text-xs font-bold mb-2">
                                <Calendar size={14} />
                                <span>日程を変更</span>
                            </div>
                            <select
                                value={selectedDate}
                                onChange={e => setSelectedDate(e.target.value)}
                                className="w-full p-2.5 bg-white dark:bg-slate-700 rounded-lg text-sm"
                            >
                                {availableDates.map((date, i) => (
                                    <option key={i} value={date.value}>{date.label}</option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* Transport: From/To Section */}
                    {isTransport && (
                        <div className="bg-indigo-50 dark:bg-indigo-900/20 rounded-xl p-3 space-y-3">
                            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 text-xs font-bold">
                                <Navigation size={14} />
                                <span>移動区間</span>
                            </div>

                            {/* From - Editable with auto-fill indicator */}
                            <div className="relative">
                                <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">
                                    出発地 {autoFrom && formData.from === autoFrom && <span className="text-indigo-500">(自動)</span>}
                                </label>
                                <div className="relative flex items-center gap-2">
                                    <input
                                        type="text"
                                        value={formData.from || ''}
                                        onChange={e => handleInputWithSuggestions('from', e.target.value)}
                                        onFocus={() => { fetchSuggestions(formData.from); setActiveSuggestionField('from'); setShowSuggestions(true); }}
                                        onBlur={closeSuggestions}
                                        className="flex-1 min-w-0 p-3 bg-white dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 text-sm font-medium"
                                        placeholder="出発地を入力..."
                                    />
                                    <button
                                        type="button"
                                        onClick={() => openMap(formData.from)}
                                        disabled={!formData.from}
                                        className="p-3 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-xl hover:bg-indigo-200 dark:hover:bg-indigo-900/50 disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
                                        title="マップで開く"
                                    >
                                        <Map size={18} />
                                    </button>
                                </div>
                                <SuggestionDropdown
                                    showSuggestions={showSuggestions}
                                    activeSuggestionField={activeSuggestionField}
                                    suggestions={suggestions}
                                    forField="from"
                                    selectSuggestion={selectSuggestion}
                                />
                            </div>

                            {/* To */}
                            <div className="relative">
                                <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">到着地</label>
                                <div className="relative flex items-center gap-2">
                                    <input
                                        type="text"
                                        value={formData.to || ''}
                                        onChange={e => handleInputWithSuggestions('to', e.target.value)}
                                        onFocus={() => { fetchSuggestions(formData.to); setActiveSuggestionField('to'); setShowSuggestions(true); }}
                                        onBlur={closeSuggestions}
                                        className="flex-1 min-w-0 p-3 bg-white dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 font-bold text-base"
                                        placeholder="到着地を入力..."
                                    />
                                    <button
                                        type="button"
                                        onClick={() => openMap(formData.to)}
                                        disabled={!formData.to}
                                        className="p-3 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-xl hover:bg-indigo-200 dark:hover:bg-indigo-900/50 disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
                                        title="マップで開く"
                                    >
                                        <Map size={18} />
                                    </button>
                                </div>
                                <SuggestionDropdown
                                    showSuggestions={showSuggestions}
                                    activeSuggestionField={activeSuggestionField}
                                    suggestions={suggestions}
                                    forField="to"
                                    selectSuggestion={selectSuggestion}
                                />
                            </div>

                            {/* Custom Display Name (Optional) */}
                            <div className="relative">
                                <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">
                                    表示名（任意）
                                </label>
                                <input
                                    type="text"
                                    value={formData.customName || ''}
                                    onChange={e => setFormData({ ...formData, customName: e.target.value })}
                                    className="w-full p-2.5 bg-white/50 dark:bg-slate-700/50 rounded-lg text-gray-700 dark:text-slate-200 text-sm border border-gray-200 dark:border-slate-600"
                                    placeholder={`未入力時: ${formData.from || '出発地'} → ${formData.to || '到着地'}`}
                                />
                                <p className="text-[10px] text-gray-400 mt-1 px-1">カード表示時のタイトルをカスタマイズできます</p>
                            </div>
                        </div>
                    )}

                    {/* Non-Transport: Name with suggestions */}
                    {!isTransport && (
                        <div className="relative">
                            <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">名称</label>
                            <div className="relative flex items-center gap-2">
                                <div className="relative flex-1">
                                    <input
                                        type="text"
                                        value={formData.name || ''}
                                        onChange={e => handleInputWithSuggestions('name', e.target.value)}
                                        onFocus={() => { fetchSuggestions(formData.name); setActiveSuggestionField('name'); setShowSuggestions(true); }}
                                        onBlur={closeSuggestions}
                                        className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 font-bold text-base pr-10 min-w-0"
                                        placeholder="場所や店名を入力..."
                                    />
                                    <Search size={16} className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400" />
                                </div>
                                <button
                                    type="button"
                                    onClick={() => openMap(formData.name)}
                                    disabled={!formData.name}
                                    className="p-3 bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 rounded-xl hover:bg-indigo-200 dark:hover:bg-indigo-900/50 disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
                                    title="マップで開く"
                                >
                                    <Map size={18} />
                                </button>
                            </div>
                            <SuggestionDropdown
                                showSuggestions={showSuggestions}
                                activeSuggestionField={activeSuggestionField}
                                suggestions={suggestions}
                                forField="name"
                                selectSuggestion={selectSuggestion}
                            />
                        </div>
                    )}

                    {/* Time */}
                    <div className="flex flex-wrap gap-3">
                        <div className="flex-1 min-w-0">
                            <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">開始</label>
                            <input
                                type="time"
                                value={formData.time || ''}
                                onChange={e => setFormData({ ...formData, time: e.target.value })}
                                className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 text-base font-medium"
                                style={{ WebkitAppearance: 'none', appearance: 'none', minWidth: 0 }}
                            />
                        </div>
                        <div className="flex-1 min-w-0">
                            <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">終了</label>
                            <input
                                type="time"
                                value={formData.endTime || ''}
                                onChange={e => setFormData({ ...formData, endTime: e.target.value })}
                                className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 text-base font-medium"
                                style={{ WebkitAppearance: 'none', appearance: 'none', minWidth: 0 }}
                            />
                        </div>
                    </div>

                    {/* Booking Reference - NEW */}
                    <div>
                        <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 flex items-center gap-1.5">
                            <Ticket size={12} />
                            予約番号
                        </label>
                        <input
                            type="text"
                            value={formData.bookingRef || ''}
                            onChange={e => setFormData({ ...formData, bookingRef: e.target.value })}
                            className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 font-mono text-base"
                            placeholder="予約番号・確認番号"
                        />
                    </div>

                    {/* Details/Memo */}
                    <div>
                        <label className="text-[10px] font-bold text-gray-400 uppercase mb-1.5 block">メモ</label>
                        <textarea
                            value={formData.details || ''}
                            onChange={e => setFormData({ ...formData, details: e.target.value })}
                            className="w-full p-3 bg-gray-50 dark:bg-slate-700 rounded-xl text-gray-800 dark:text-slate-100 h-20 resize-none text-sm leading-relaxed"
                            placeholder="座席情報、注意事項など"
                        />
                    </div>
                </div>

                {/* Footer */}
                <div className="p-4 border-t border-gray-100 dark:border-slate-700 flex gap-3 shrink-0 pb-[calc(1rem+env(safe-area-inset-bottom))] sm:pb-4">
                    {item && onDelete && (
                        <button
                            onClick={() => onDelete(item.id)}
                            className="p-3 bg-red-50 dark:bg-red-900/30 text-red-600 rounded-xl hover:bg-red-100 active:scale-95 transition-all"
                        >
                            <Trash2 size={20} />
                        </button>
                    )}
                    <button
                        onClick={() => {
                            const dataToSave = { ...formData };

                            // Explicitly preserve empty strings for clearable fields
                            // This ensures that clearing a field (making it blank) is saved properly
                            const clearableFields = ['bookingRef', 'details', 'endTime', 'address'];
                            clearableFields.forEach(field => {
                                if (field in formData && (formData[field] === '' || formData[field] === undefined)) {
                                    dataToSave[field] = '';  // Explicitly set empty string
                                }
                            });

                            // Handle transport event naming logic
                            if (isTransport) {
                                // Use customName if provided, otherwise auto-generate from "from → to"
                                if (formData.customName && formData.customName.trim()) {
                                    dataToSave.name = formData.customName.trim();
                                } else if (formData.from && formData.to) {
                                    dataToSave.name = `${formData.from} → ${formData.to}`;
                                } else if (formData.to) {
                                    dataToSave.name = formData.to;
                                } else {
                                    dataToSave.name = formData.from || '';
                                }
                                // Remove customName from saved data (internal field only)
                                delete dataToSave.customName;
                            }

                            // Only set up move operation if both dates are valid
                            if (selectedDate && currentDate && selectedDate !== currentDate) {
                                dataToSave.newDate = selectedDate;
                                dataToSave.originalDate = currentDate;
                            }
                            onSave(dataToSave);
                        }}
                        className="flex-1 bg-indigo-600 text-white font-bold py-3 rounded-xl hover:bg-indigo-700 flex items-center justify-center gap-2 active:scale-[0.98] transition-all shadow-lg shadow-indigo-500/20"
                    >
                        <Save size={18} />
                        保存する
                    </button>
                </div>
            </div>
        </div>
    );
};

// Extracted SuggestionDropdown component
const SuggestionDropdown = ({ showSuggestions, activeSuggestionField, suggestions, forField, selectSuggestion }) => {
    if (!showSuggestions || activeSuggestionField !== forField || suggestions.length === 0) return null;
    return (
        <div className="absolute z-50 w-full mt-1 bg-white dark:bg-slate-700 rounded-xl shadow-lg border border-gray-200 dark:border-slate-600 max-h-48 overflow-y-auto">
            {suggestions.map((s, i) => {
                const description = typeof s === 'string' ? s : s.description;
                return (
                    <button
                        key={i}
                        type="button"
                        className="w-full text-left px-4 py-3 hover:bg-gray-100 dark:hover:bg-slate-600 text-sm text-gray-700 dark:text-slate-200 flex items-center gap-2 border-b border-gray-100 dark:border-slate-600 last:border-0"
                        onMouseDown={() => selectSuggestion(s)}
                    >
                        <MapPin size={14} className="text-indigo-500 shrink-0" />
                        <span className="truncate min-w-0 flex-1">{description}</span>
                    </button>
                );
            })}
        </div>
    );
};

export default EditModal;
